# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86c8b969b08bbbb45410be989e47ed0497fdfcf566a8258e257d7531084f8f367a498656aea293c44eca5f4880e1c9d80c839a6fb9fe8bd5cd179d950eafb0f7

test:
  secret_key_base: f80e75e17c61c8815966342f574eaadccaa593629f526bca1b9a7a82e834975db9d9ee0b9304b4ef6665bcabe43fbfe8e5b1deb61c9514a936e40b6964f827c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
